services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: subscriptiontracker-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuaSenhaForte123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: